# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uberEats', '0002_auto_20171201_0220'),
    ]

    operations = [
        migrations.CreateModel(
            name='UbereatsVendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('cuisine', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'uberEats_vendor',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'managed': False},
        ),
    ]
