# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 21:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uberEats', '0003_auto_20171201_0331'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vendor',
            table='vendor',
        ),
    ]
