# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-05 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_blocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='name',
            field=models.CharField(default='ayyyyyy', max_length=250),
            preserve_default=False,
        ),
    ]
