# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 21:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stacker', '0002_auto_20171216_2135'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stack',
            table='stacker',
        ),
    ]
