# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 21:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stacker', '0003_auto_20171216_2141'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stack',
            table='stack',
        ),
    ]
