# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 21:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stacker', '0004_auto_20171216_2148'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stack',
            table='stacker_stack',
        ),
    ]
