# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacker', '0007_remove_stack_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stack',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='stack',
            name='goal',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterModelTable(
            name='stack',
            table=None,
        ),
    ]
